# Generated by Django 5.0.3 on 2024-03-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255, verbose_name='Product')),
                ('unit', models.CharField(default='ea', max_length=255, verbose_name='Unit')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='Vendor')),
                ('product_is_delete', models.BooleanField(default=False)),
                ('material', models.CharField(blank=True, choices=[('NATURAL QUARTZITE', 'Natural Quartzite'), ('ENGINEERED QUARTZ', 'Engineered Quartz'), ('GRANITE', 'Granite'), ('MARBLE', 'Marble'), ('DOLOMITE', 'Dolomite'), ('SOAPSTONE', 'Soapstone'), ('OTHER', 'Other')], max_length=255, verbose_name='Material')),
            ],
        ),
    ]
